---
Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/BlockLength:
  Max: 20
  Exclude:
    - 'spec/*'
    - 'spec/**/*'

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 250

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 250

Metrics/ParameterLists:
  Max: 5
