default: &default
  adapter: <%= ENV.fetch("DB_ADAPTER") { "mysql2" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['PERCONA_DB_USER'] || 'root' %>
  password: <%= ENV['PERCONA_DB_PASSWORD'] || 'password' %>
  hostname: <%= ENV['PERCONA_DB_HOST'] || 'localhost' %>
  socket: <%= ENV['PERCONA_DB_SOCKET'] || '' %>
  database: <%= ENV['PERCONA_DB_NAME'] || 'departure_test' %>
  advisory_locks: false

# Setting these envs to be the same as the default database
# we have some code paths where rails env is test or development in tests
development:
  <<: *default

test:
  <<: *default
